# Урок 1. Основные понятия и структуры PyTorch

- Создайте случайный FloatTensor размера 3x4x5
- Выведите его форму (shape)
- Приведите его к форме 6х10
- Создайте случайный IntTensor размера 10
- Умножьте созданный FloatTensor на созданный IntTensor поэлементно
- Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
- Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
- Создайте единичный тензор размера 5x6
- Переведите его в формат numpy

In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [3]:
t = torch.randn(3, 4, 5)
t

tensor([[[-1.0213,  1.2186, -0.8315, -0.0614, -0.2352],
         [ 1.7629, -1.4459, -1.6042,  0.8479,  0.6779],
         [-0.0191, -0.7755,  1.9118,  2.3433,  0.4388],
         [-0.8338,  0.2255,  1.2231,  0.2390, -0.3577]],

        [[ 0.9439,  1.2482,  0.7746,  2.3472, -0.6944],
         [-1.6561,  1.8975, -0.9142,  0.0350, -1.1759],
         [ 0.1603,  1.1399, -1.0824, -0.6283, -0.1768],
         [-0.8398, -0.0762, -0.6822,  0.7288,  0.6056]],

        [[-1.0635,  1.2662, -1.6779,  0.7147, -0.4118],
         [-0.3750, -0.6639, -0.5470,  0.7468, -0.7304],
         [-0.2473,  0.3452,  0.8080,  0.2862, -0.8162],
         [ 0.4143, -1.4811, -0.6284,  0.3708, -1.5943]]])

In [4]:
# Выведите его форму (shape)

In [5]:
t.shape

torch.Size([3, 4, 5])

In [6]:
# Приведите его к форме 6 X 10

In [7]:
t = t.view(6, 10)
t

tensor([[-1.0213,  1.2186, -0.8315, -0.0614, -0.2352,  1.7629, -1.4459, -1.6042,
          0.8479,  0.6779],
        [-0.0191, -0.7755,  1.9118,  2.3433,  0.4388, -0.8338,  0.2255,  1.2231,
          0.2390, -0.3577],
        [ 0.9439,  1.2482,  0.7746,  2.3472, -0.6944, -1.6561,  1.8975, -0.9142,
          0.0350, -1.1759],
        [ 0.1603,  1.1399, -1.0824, -0.6283, -0.1768, -0.8398, -0.0762, -0.6822,
          0.7288,  0.6056],
        [-1.0635,  1.2662, -1.6779,  0.7147, -0.4118, -0.3750, -0.6639, -0.5470,
          0.7468, -0.7304],
        [-0.2473,  0.3452,  0.8080,  0.2862, -0.8162,  0.4143, -1.4811, -0.6284,
          0.3708, -1.5943]])

In [8]:
# Создайте случайный IntTensor размера 10

In [9]:
torch.IntTensor(10)

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=torch.int32)

In [10]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [11]:
t = t.matmul(t.t())
t

tensor([[12.2291, -6.5601, -5.0318,  2.9582,  5.3918,  3.2893],
        [-6.5601, 12.3673,  6.8101, -4.7001, -2.7418,  0.8051],
        [-5.0318,  6.8101, 17.6036,  0.5668,  1.9870,  1.0277],
        [ 2.9582, -4.7001,  0.5668,  4.9971,  3.5535, -1.0579],
        [ 5.3918, -2.7418,  1.9870,  3.5535,  8.2020,  2.4981],
        [ 3.2893,  0.8051,  1.0277, -1.0579,  2.4981,  7.0207]])

In [12]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [13]:
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t
y.backward()

print('d(y)/d(x) =', x.grad.item())
print('d(y)/d(z) =', z.grad.item())
print('d(y)/d(t) =', t.grad.item())


d(y)/d(x) = 3.0
d(y)/d(z) = 1.0
d(y)/d(t) = -75.0


In [14]:
# Создайте единичный тензор размера 5x6

In [15]:
t = torch.eye(5, 6)
t

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [16]:
# Переведите его в формат numpy

In [17]:
t.numpy()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)